# Generated by Django 4.2.5 on 2023-09-06 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bottle_size', models.FloatField()),
                ('bottles_per_crate', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate_amount', models.IntegerField()),
                ('brand_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='db_access.brand')),
                ('delivery_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='db_access.delivery')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_access.transaction'),
        ),
    ]
