# Generated by Django 4.2.5 on 2023-09-07 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate_amount', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_access.brand')),
            ],
        ),
        migrations.AlterField(
            model_name='delivery',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_access.transaction'),
        ),
        migrations.DeleteModel(
            name='Delivery_Brands',
        ),
        migrations.AddField(
            model_name='branddelivery',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_deliveries', to='db_access.delivery'),
        ),
    ]
