# Generated by Django 4.2.4 on 2023-09-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_access', '0002_branddelivery_alter_delivery_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_amount', models.PositiveIntegerField(verbose_name='amount of bottles')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='db_access.brand')),
            ],
        ),
    ]
