# Generated by Django 4.2.5 on 2023-09-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_access', '0003_alter_brand_name_alter_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('name', 'bottle_size')},
        ),
    ]
