# Generated by Django 4.2.4 on 2023-09-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_access', '0003_inventory'),
        ('db_access', '0004_alter_brand_name_alter_brand_unique_together'),
    ]

    operations = [
    ]
