# Generated by Django 4.2.4 on 2023-09-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_access', '0005_merge_20230922_1536'),
        ('db_access', '0006_rename_inventory_inventoryitem'),
    ]

    operations = [
    ]
