# Generated by Django 4.2.4 on 2024-04-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_access', '0007_merge_20230922_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='bottle_size',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='bottles_per_crate',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='brand_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('brand_name', 'bottle_size')},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='brand',
        ),
    ]
