# Generated by Django 4.2.4 on 2024-04-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_access', '0008_inventoryitem_bottle_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='bottles_per_crate',
            new_name='crate_size',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='brand_name',
            field=models.CharField(default='not defined', max_length=200),
            preserve_default=False,
        ),
    ]
