# Generated by Django 4.2.4 on 2024-05-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_access', '0009_rename_bottles_per_crate_inventoryitem_crate_size_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branddelivery',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='branddelivery',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='branddelivery',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='cost',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='BrandDelivery',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
